title: Faryal Zaidi
logo: /Fari Pic.jpg
description: Data Scientist
#show_downloads: true
theme: jekyll-theme-minimal

<img src="{{ site.logo }}" class="logo-circle" alt="Profile Picture">

.logo-circle {
  border-radius: 50%; /* Makes the image circular */
  width: 150px; /* Adjust the width as needed */
  height: 150px; /* Adjust the height as needed */
}
